name: Security Scan

on:
  workflow_call:
    inputs:
      fetch_depth:
        description: 'Git fetch depth (0 for full history)'
        required: false
        type: number
        default: 0

permissions:
  contents: read
  pull-requests: read

jobs:
  trufflehog:
    name: Secret Scan (Trufflehog)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: ${{ inputs.fetch_depth }}
          persist-credentials: false

      - name: Run Trufflehog
        uses: trufflesecurity/trufflehog@6961f2bace57ab32b23b3ba40f8f420f6bc7e004 # main
        with:
          path: .
          extra_args: --results=verified,unknown
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
